events {}

http {
	server {
		listen 443 ssl;

		# Serv Info
		server_name $DOMAIN_NAME;
		root /var/www/wordpress;
		index index.php;

		# Certificats TLS
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		# Version TLS
		ssl_protocols TLSv1.2 TLSv1.3;

		# Default Location
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Location PHP
		location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass wordpress:9000;
		}
	}
}

