events {}

http {
	server {
		listen 443 ssl;

		# Serv Info
		server_name alde-abr.42.fr;
		root /var/www/wordpress;
		index index.php index.html;

		# Certificats TLS
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		# Version TLS
		ssl_protocols TLSv1.2 TLSv1.3;

		# Default Location
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Location PHP
		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_index index.php;
		}
	}
}

